# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaultContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='\u6545\u969c\u540d\u79f0')),
                ('level', models.IntegerField(choices=[(0, 'P0'), (1, 'P1'), (2, 'P2'), (3, 'P3'), (4, 'P4')], verbose_name='\u6545\u969c\u7ea7\u522b')),
                ('effect', models.TextField(blank=True, null=True, verbose_name='\u6545\u969c\u5f71\u54cd')),
                ('reasons', models.TextField(blank=True, null=True, verbose_name='\u6545\u969c\u539f\u56e0')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='\u89e3\u51b3\u65b9\u6848')),
                ('content', models.TextField(blank=True, null=True, verbose_name='\u5904\u7406\u6d41\u7a0b')),
                ('status', models.IntegerField(choices=[(0, '\u5904\u7406\u4e2d'), (1, '\u6539\u8fdb\u4e2d'), (2, '\u5df2\u6062\u590d'), (3, '\u5df2\u5b8c\u7ed3')], verbose_name='\u6545\u969c\u72b6\u6001')),
                ('improve', models.IntegerField(choices=[(0, '\u5f00\u53d1'), (1, '\u8fd0\u7ef4'), (2, '\u673a\u623f'), (3, '\u7f51\u7edc'), (4, '\u5176\u4ed6')], verbose_name='\u4e3b\u5bfc\u6539\u8fdb')),
                ('lesson', models.TextField(blank=True, verbose_name='\u7ecf\u9a8c\u603b\u7ed3')),
                ('start_time', models.DateTimeField(verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_time', models.DateTimeField(verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('create_datetime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'fault_content',
            },
        ),
        migrations.CreateModel(
            name='FaultsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6545\u969c\u5206\u7c7b')),
            ],
            options={
                'db_table': 'faults_type',
            },
        ),
        migrations.CreateModel(
            name='FaultsProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u6545\u969c\u9879\u76ee')),
            ],
            options={
                'db_table': 'faults_project',
            },
        ),
        migrations.AddField(
            model_name='faultcontent',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faults.FaultsProject', verbose_name='\u5f71\u54cd\u9879\u76ee'),
        ),
        migrations.AddField(
            model_name='faultcontent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faults.FaultsClass', verbose_name='\u6545\u969c\u7c7b\u578b'),
        ),
    ]
