# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faults', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FaultContent',
            new_name='FaultsContent',
        ),
    ]
