# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-28 16:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_model', models.CharField(blank=True, max_length=128, verbose_name='CPU\u578b\u53f7')),
                ('cpu_count', models.SmallIntegerField(verbose_name='\u7269\u7406CPU\u4e2a\u6570')),
                ('cpu_core_count', models.SmallIntegerField(verbose_name='\u903b\u8f91CPU\u6838\u6570')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
            options={
                'db_table': 'hosts_cpu',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('slot', models.CharField(max_length=64, verbose_name='\u63d2\u69fd\u4f4d')),
                ('manufactory', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5236\u9020\u5546')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u78c1\u76d8\u578b\u53f7')),
                ('capacity', models.FloatField(verbose_name='\u78c1\u76d8\u5bb9\u91cfGB')),
                ('iface_type', models.CharField(choices=[(b'SATA', b'SATA'), (b'SAS', b'SAS'), (b'SCSI', b'SCSI'), (b'SSD', b'SSD')], default=b'SAS', max_length=64, verbose_name='\u63a5\u53e3\u7c7b\u578b')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
            ],
        ),
        migrations.CreateModel(
            name='HostCabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u673a\u67dc')),
                ('status', models.BooleanField(default=0, verbose_name='\u673a\u67dc\u72b6\u6001')),
            ],
            options={
                'db_table': 'hosts_cabinet',
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u4e3b\u673a\u7ec4')),
            ],
            options={
                'db_table': 'hosts_groups',
            },
        ),
        migrations.CreateModel(
            name='HostIDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='\u673a\u623f')),
                ('address', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5730\u5740')),
            ],
            options={
                'db_table': 'hosts_idc',
            },
        ),
        migrations.CreateModel(
            name='Manufactory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufactory', models.CharField(max_length=64, unique=True, verbose_name='\u5382\u5546\u540d\u79f0')),
                ('support_num', models.CharField(blank=True, max_length=30, verbose_name='\u652f\u6301\u7535\u8bdd')),
            ],
            options={
                'db_table': 'hosts_manufactory',
            },
        ),
        migrations.CreateModel(
            name='NIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7f51\u5361\u540d')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u7f51\u5361\u578b\u53f7')),
                ('macaddress', models.CharField(max_length=64, unique=True, verbose_name='MAC')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('netmask', models.CharField(blank=True, max_length=64, null=True)),
                ('bonding', models.CharField(blank=True, max_length=64, null=True)),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'hosts_network',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('model', models.CharField(max_length=128, verbose_name='\u5185\u5b58\u578b\u53f7')),
                ('slot', models.CharField(max_length=64, verbose_name='\u63d2\u69fd')),
                ('capacity', models.IntegerField(verbose_name='\u5185\u5b58\u5927\u5c0f(MB)')),
                ('memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
            options={
                'db_table': 'hosts_memory',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(blank=True, max_length=128, null=True, verbose_name='SN\u53f7')),
                ('hostname', models.CharField(max_length=128, unique=True, verbose_name='\u4e3b\u673a\u540d\u79f0')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='\u516c\u7f51\u5730\u5740')),
                ('nip_address', models.GenericIPAddressField(unique=True, verbose_name='\u5185\u7f51\u5730\u5740')),
                ('server_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u670d\u52a1\u5668\u578b\u53f7')),
                ('system_distribution', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53d1\u884c\u7248\u672c')),
                ('system_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7c7b\u578b')),
                ('system_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('kernel_release', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u5185\u6838\u7248\u672c')),
                ('create_datetime', models.DateTimeField(auto_now=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_datetime', models.DateTimeField(auto_now_add=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('trade_datetime', models.DateTimeField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4')),
                ('expire_datetime', models.DateTimeField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u4fee\u671f')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_admin', to=settings.AUTH_USER_MODEL)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cabinet_name', to='assets.HostCabinet')),
                ('group', models.ManyToManyField(related_name='group_name', to='assets.HostGroup')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idc_name', to='assets.HostIDC')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_manager', to=settings.AUTH_USER_MODEL)),
                ('manufactory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufactory_name', to='assets.Manufactory')),
            ],
            options={
                'db_table': 'hosts_servers',
            },
        ),
        migrations.AddField(
            model_name='ram',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Server'),
        ),
        migrations.AddField(
            model_name='nic',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Server'),
        ),
        migrations.AddField(
            model_name='hostcabinet',
            name='idc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.HostIDC', verbose_name='\u673a\u623f\u5730\u5740'),
        ),
        migrations.AddField(
            model_name='disk',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Server'),
        ),
        migrations.AddField(
            model_name='cpu',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.Server'),
        ),
    ]
