# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-11 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='system_distribution',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='\u53d1\u884c\u7248\u672c'),
        ),
        migrations.AlterField(
            model_name='server',
            name='expire_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u8fc7\u4fdd\u4fee\u671f'),
        ),
        migrations.AlterField(
            model_name='server',
            name='trade_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u8d2d\u4e70\u65f6\u95f4'),
        ),
    ]
