# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0002_auto_20180811_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpu',
            name='server_address',
        ),
        migrations.RemoveField(
            model_name='disk',
            name='server_address',
        ),
        migrations.RemoveField(
            model_name='nic',
            name='server_address',
        ),
        migrations.RemoveField(
            model_name='ram',
            name='server_address',
        ),
        migrations.AddField(
            model_name='cpu',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Server'),
        ),
        migrations.AddField(
            model_name='disk',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Server'),
        ),
        migrations.AddField(
            model_name='nic',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Server'),
        ),
        migrations.AddField(
            model_name='ram',
            name='hostname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='CMDB.Server'),
        ),
        migrations.AlterField(
            model_name='hostsaddress',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='\u516c\u7f51\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='hostsaddress',
            name='nip',
            field=models.GenericIPAddressField(unique=True, verbose_name='\u5185\u7f51\u5730\u5740'),
        ),
    ]
