# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-25 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMDB', '0003_auto_20180924_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosts',
            name='cabinet',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='group',
        ),
        migrations.RemoveField(
            model_name='hosts',
            name='idc',
        ),
        migrations.DeleteModel(
            name='HostsAddress',
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True, verbose_name='\u516c\u7f51\u5730\u5740'),
        ),
        migrations.DeleteModel(
            name='Hosts',
        ),
    ]
