# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-21 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bind', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dns',
            name='zone',
            field=models.CharField(choices=[(0, b'linux-testing.com')], default=0, max_length=128, verbose_name='Zone'),
        ),
        migrations.DeleteModel(
            name='Zone',
        ),
    ]
