# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-23 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bind', '0002_auto_20190121_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dns',
            name='zone',
            field=models.IntegerField(choices=[(0, b'linux-testing.com')], default=0, verbose_name='Zone'),
        ),
    ]
