# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-12 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=128, verbose_name='\u57df\u540d')),
                ('host', models.CharField(max_length=128, verbose_name='\u8bb0\u5f55\u540d\u79f0')),
                ('type', models.CharField(choices=[(b'A', b'A- \xe5\xb0\x86\xe5\x9f\x9f\xe5\x90\x8d\xe6\x8c\x87\xe5\x90\x91\xe4\xb8\x80\xe4\xb8\xaaIPV4\xe5\x9c\xb0\xe5\x9d\x80')], default=b'A', max_length=128, verbose_name='\u8bb0\u5f55\u7c7b\u578b')),
                ('data', models.CharField(max_length=128, verbose_name='\u8bb0\u5f55\u503c')),
                ('ttl', models.IntegerField(verbose_name='TTL\u65f6\u95f4')),
                ('mx_priority', models.IntegerField(blank=True, null=True, verbose_name='MX\u4f18\u5148\u7ea7')),
                ('refresh', models.IntegerField(blank=True, null=True, verbose_name='\u5237\u65b0\u65f6\u95f4\u95f4\u9694')),
                ('retry', models.IntegerField(blank=True, null=True, verbose_name='\u91cd\u8bd5\u65f6\u95f4\u95f4\u9694')),
                ('expire', models.IntegerField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4')),
                ('minimum', models.IntegerField(blank=True, null=True, verbose_name='\u6700\u5c0f\u65f6\u95f4')),
                ('serial', models.IntegerField(blank=True, null=True, verbose_name='\u5e8f\u5217\u53f7')),
                ('resp_person', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u8d23\u4efb\u4eba')),
                ('status', models.BooleanField(default=1, verbose_name='\u8bb0\u5f55\u72b6\u6001')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
            options={
                'db_table': 'dns_records',
            },
        ),
    ]
