# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-10 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DNS', '0002_auto_20180812_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u57df\u540d')),
            ],
            options={
                'db_table': 'dns_zone',
            },
        ),
        migrations.AlterField(
            model_name='dns',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DNS.Zone', verbose_name='\u57df\u540d'),
        ),
    ]
