# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-10 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DNS', '0003_auto_20181010_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='create_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
    ]
